# Generated by Django 5.2.2 on 2026-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='instancia',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
